name: "Check PyPI Packaging"

on:
  push:
    branches-ignore:
      - "master"
  pull_request:

jobs:
  check_pypi_packaging:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Build and publish
        run: |
          python setup.py sdist bdist_wheel
