name: "Docs Check"
on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"
        pre-build-command: "pip3 install sphinx_rtd_theme"
        build-command: "sphinx-build -T -E -W -b html . _build"
