name: "Docs Check"
on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install sphinx
      run: apt-get install python3-sphinx
    - name: Install sphinx_rtd_theme
      run: pip3 install sphinx_rtd_theme
    - name: Run sphinx
      run: (cd doc; sphinx-build -T -E -W -b html . _build)
