name: "Docs Check"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Install theme
      run: pip3 install sphinx_rtd_theme
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"
